/* Generated by Amaranth Yosys 0.40 (PyPI ver 0.40.0.0.post95, git sha1 a1bb0255d) */

(* top =  1  *)
(* generator = "Amaranth" *)
module top(phase_bit, input_fock_state);
  reg \$auto$verilog_backend.cc:2352:dump_module$1  = 0;
  (* src = "/home/daquintero/phd/piel_private/piel/tools/amaranth/construct.py:48" *)
  input [2:0] input_fock_state;
  wire [2:0] input_fock_state;
  (* src = "/home/daquintero/phd/piel_private/piel/tools/amaranth/construct.py:48" *)
  output [9:0] phase_bit;
  reg [9:0] phase_bit;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/daquintero/phd/piel_private/piel/tools/amaranth/construct.py:62" *)
    casez (input_fock_state)
      /* src = "/home/daquintero/phd/piel_private/piel/tools/amaranth/construct.py:65" */
      3'h4:
          phase_bit = 10'h000;
      /* src = "/home/daquintero/phd/piel_private/piel/tools/amaranth/construct.py:65" */
      3'h1:
          phase_bit = 10'h3e0;
      /* src = "/home/daquintero/phd/piel_private/piel/tools/amaranth/construct.py:65" */
      3'h2:
          phase_bit = 10'h01f;
      /* src = "/home/daquintero/phd/piel_private/piel/tools/amaranth/construct.py:69" */
      default:
          phase_bit = 10'h000;
    endcase
  end
endmodule
