#!/bin/bash 
# Makefile 
SIM ?= icarus 
TOPLEVEL_LANG ?= verilog 
VERILOG_SOURCES += /home/daquintero/phd/piel_private/docs/examples/10_demo_full_flow/full_flow_demo/full_flow_demo/src/truth_table_module.v 
TOPLEVEL := top 
MODULE := test_top 
include $(shell cocotb-config --makefiles)/Makefile.sim